name: Update ZOE outage page

on:
  schedule:
    - cron: "0 */3 * * *"   # каждые 3 часа
  workflow_dispatch:       # запуск вручную

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download outage page
        run: |
          curl -L https://www.zoe.com.ua/outage/ \
            -H "User-Agent: Mozilla/5.0" \
            -o latest.html

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          if git diff --quiet; then
            echo "No changes"
          else
            git add latest.html
            git commit -m "Update outage page"
            git push
          fi
